const recommendations = [
    'The building sewer / lateral sewer line/pipe should be replaced.',
    'The building sewer / lateral sewer line/pipe should be replaced using the dig and trench method.',
    'The building sewer / lateral sewer line/pipe should be replaced using the pipe burst method.',
    'The building sewer / lateral sewer line/pipe should be relined using a CIPP (cured in place pipe).',
    'Approximately {num} feet of the building sewer / lateral sewer line should be replaced.',
    'Approximately {num} feet of the building sewer / lateral sewer line should be relined using a CIPP (cured in place pipe).',
    'A partial CIPP (cured in place pipe) should be installed in the building sewer / lateral sewer line/pipe at approximately {num} feet.',
    'Exterior clean-outs should be installed in the building sewer / lateral sewer line near the house.',
    'The interior section of the building drain / main sewer line/pipe should be replaced.',
    'The cast iron portion of the building drain / main sewer line/pipe should be cleaned.',
    'The cast iron portion of the building drain / main sewer line/pipe should be cleaned with metal blades.',
    'The cast iron portion of the building drain / main sewer line/pipe should be cleaned by hydro-jetting.',
    'The cast iron portion of the building drain / main sewer line/pipe should be cleaned by air-jetting.',
    'The building drain / main sewer line/pipe should be cleaned and re-inspected with a camera.',
    'The interior main sewer line / pipe clean-out fitting should be replaced.',
    'The in-yard portion of the building sewer / lateral sewer line/pipe should be replaced, the under-road portion of the building sewer / lateral sewer line/pipe should be relined using a CIPP (cured in place pipe).',
    'The in-yard portion of the building sewer / lateral sewer line/pipe should be replaced using the dig and trench method, the under-road portion of the building sewer / lateral sewer line/pipe should be relined using a CIPP (cured in place pipe).',
    'The in-yard portion of the building sewer / lateral sewer line/pipe should be replaced using the pipe burst method, the under-road portion of the building sewer / lateral sewer line/pipe should be relined using a CIPP (cured in place pipe).',
    'The transition from building drain to building sewer should be repaired.',
    'The main sewer line/pipe should be cleaned for roots and re-inspected with a camera before the inspection objection deadline, Real Estate contract deadline date; please consult with your Real Estate Professional / Realtor.',
    'The main sewer line/pipe should be cleaned for roots annually to minimize the potential for blockage.',
    'The main sewer line/pipe should be cleaned of scale / hydro-jetted and re-inspected with a camera before the inspection objection deadline, Real Estate contract deadline date; please consult with your Real Estate Professional / Realtor.',
    'The main sewer line/pipe should be repaired or replaced as needed and re-inspected with a camera before the inspection objection deadline, Real Estate contract deadline date; please consult with your Real Estate Professional / Realtor.',
    'The main sewer line/pipe should be hydro-jetted and repaired as needed and re-inspected with a camera before the inspection objection deadline, Real Estate contract deadline date; please consult with your Real Estate Professional / Realtor.',
    'The main sewer line/pipe appeared to be Orangeburg / Bermico (Bituminous fiber pipe); the main sewer line should be replaced before the inspection objection deadline, Real Estate contract deadline date; please consult with your Real Estate Professional / Realtor.',
    'The exterior main sewer line/pipe showed evidence of past cleanings; consult with the Real Estate Professional / Seller as to the frequency of maintenance performed to estimate costs / expenses related to continued maintenance.',
    'The city tap should be evaluated by the local water district and repaired as needed before the inspection objection deadline, Real Estate contract deadline date; please consult with your Real Estate Professional / Realtor.',
    'The main sewer line/pipe should be cleaned of scale / hydro-jetted and re-inspected with a camera for damage and repaired or replaced as needed before the inspection objection deadline, Real Estate contract deadline date; please consult with your Real Estate Professional / Realtor.',
    'Proper clean-outs should be provided / added.',
];